// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGHKqYnXKoIp4E5g3NZdKooLkbHTFxy8Y',
    appId: '1:1041680729524:web:1aa65098b87a17d4cfdee1',
    messagingSenderId: '1041680729524',
    projectId: 'restise-dae1b',
    authDomain: 'restise-dae1b.firebaseapp.com',
    storageBucket: 'restise-dae1b.firebasestorage.app',
    measurementId: 'G-4ETQ75PY5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJS6CJLgM1T6EtlIgARM5PWbTXZIXc3bk',
    appId: '1:1041680729524:android:c6b13275a5256906cfdee1',
    messagingSenderId: '1041680729524',
    projectId: 'restise-dae1b',
    storageBucket: 'restise-dae1b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURiC5mBcsIfvGP0ctJQoxE_R4prX2xvI',
    appId: '1:1041680729524:ios:5d6334ead34c5241cfdee1',
    messagingSenderId: '1041680729524',
    projectId: 'restise-dae1b',
    storageBucket: 'restise-dae1b.firebasestorage.app',
    iosBundleId: 'com.example.hastayimm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURiC5mBcsIfvGP0ctJQoxE_R4prX2xvI',
    appId: '1:1041680729524:ios:5d6334ead34c5241cfdee1',
    messagingSenderId: '1041680729524',
    projectId: 'restise-dae1b',
    storageBucket: 'restise-dae1b.firebasestorage.app',
    iosBundleId: 'com.example.hastayimm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGHKqYnXKoIp4E5g3NZdKooLkbHTFxy8Y',
    appId: '1:1041680729524:web:7da3aa4ac1f8c42dcfdee1',
    messagingSenderId: '1041680729524',
    projectId: 'restise-dae1b',
    authDomain: 'restise-dae1b.firebaseapp.com',
    storageBucket: 'restise-dae1b.firebasestorage.app',
    measurementId: 'G-JPVC4YHXW5',
  );
}
